## Switches
set_property PACKAGE_PIN V17 [get_ports {HEX[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {HEX[0]}]
set_property PACKAGE_PIN V16 [get_ports {HEX[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {HEX[1]}]
set_property PACKAGE_PIN W16 [get_ports {HEX[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {HEX[2]}]
set_property PACKAGE_PIN W17 [get_ports {HEX[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {HEX[3]}]
#set_property PACKAGE_PIN W15 [get_ports {sw[4]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[4]}]
#set_property PACKAGE_PIN V15 [get_ports {sw[5]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[5]}]
#set_property PACKAGE_PIN W14 [get_ports {sw[6]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[6]}]
#set_property PACKAGE_PIN W13 [get_ports {sw[7]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]
#set_property PACKAGE_PIN V2 [get_ports {sw[8]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[8]}]
#set_property PACKAGE_PIN T3 [get_ports {sw[9]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[9]}]
#set_property PACKAGE_PIN T2 [get_ports {sw[10]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[10]}]
#set_property PACKAGE_PIN R3 [get_ports {sw[11]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[11]}]
set_property PACKAGE_PIN W2 [get_ports {enableN[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {enableN[0]}]
set_property PACKAGE_PIN U1 [get_ports {enableN[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {enableN[1]}]
set_property PACKAGE_PIN T1 [get_ports {enableN[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {enableN[2]}]
set_property PACKAGE_PIN R2 [get_ports {enableN[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {enableN[3]}]

	
#7 segment display
set_property PACKAGE_PIN W7 [get_ports {SEVEN_SEG[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SEVEN_SEG[6]}]
set_property PACKAGE_PIN W6 [get_ports {SEVEN_SEG[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SEVEN_SEG[5]}]
set_property PACKAGE_PIN U8 [get_ports {SEVEN_SEG[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SEVEN_SEG[4]}]
set_property PACKAGE_PIN V8 [get_ports {SEVEN_SEG[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SEVEN_SEG[3]}]
set_property PACKAGE_PIN U5 [get_ports {SEVEN_SEG[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SEVEN_SEG[2]}]
set_property PACKAGE_PIN V5 [get_ports {SEVEN_SEG[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SEVEN_SEG[1]}]
set_property PACKAGE_PIN U7 [get_ports {SEVEN_SEG[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SEVEN_SEG[0]}]

set_property PACKAGE_PIN U2 [get_ports {ANODES[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {ANODES[0]}]
set_property PACKAGE_PIN U4 [get_ports {ANODES[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {ANODES[1]}]
set_property PACKAGE_PIN V4 [get_ports {ANODES[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {ANODES[2]}]
set_property PACKAGE_PIN W4 [get_ports {ANODES[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {ANODES[3]}]
 